services:
  app:
    build: .
    container_name: controle_financeiro_app
    ports:
      - "8520:8520"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/controle_financeiro.db
    restart: unless-stopped
