services:
  app:
    build: .
    container_name: controle_financeiro_app
    ports:
      # Mapeia a porta 8521 do seu host (sua máquina) para a porta 8521 interna do container
      - "8521:8521"
    env_file:
      - .env
    volumes:
      # CORREÇÃO: Cria uma pasta de dados dedicada no container (ex: /app/data)
      # Isso evita que o volume limpe o código fonte que está na raiz (/app)
      - ./data:/app/data
    restart: unless-stopped
