"""banco_unificado_v1

Revision ID: bb8a7514b4ee
Revises: 
Create Date: 2026-07-07 11:30:56.008821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb8a7514b4ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('is_protegido', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_id'), 'tipos', ['id'], unique=False)
    op.create_index(op.f('ix_tipos_nome'), 'tipos', ['nome'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('totp_secret', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_protegido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_index(op.f('ix_categorias_nome'), 'categorias', ['nome'], unique=False)
    op.create_index(op.f('ix_categorias_owner_id'), 'categorias', ['owner_id'], unique=False)
    op.create_index(op.f('ix_categorias_tipo_id'), 'categorias', ['tipo_id'], unique=False)
    op.create_table('investment_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_assets_company'), 'investment_assets', ['company'], unique=False)
    op.create_index(op.f('ix_investment_assets_id'), 'investment_assets', ['id'], unique=False)
    op.create_index(op.f('ix_investment_assets_owner_id'), 'investment_assets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_investment_assets_ticker'), 'investment_assets', ['ticker'], unique=False)
    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('pago', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacoes_ano'), 'transacoes', ['ano'], unique=False)
    op.create_index(op.f('ix_transacoes_categoria'), 'transacoes', ['categoria'], unique=False)
    op.create_index(op.f('ix_transacoes_id'), 'transacoes', ['id'], unique=False)
    op.create_index(op.f('ix_transacoes_item'), 'transacoes', ['item'], unique=False)
    op.create_index(op.f('ix_transacoes_mes'), 'transacoes', ['mes'], unique=False)
    op.create_index(op.f('ix_transacoes_owner_id'), 'transacoes', ['owner_id'], unique=False)
    op.create_index(op.f('ix_transacoes_tipo'), 'transacoes', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transacoes_tipo'), table_name='transacoes')
    op.drop_index(op.f('ix_transacoes_owner_id'), table_name='transacoes')
    op.drop_index(op.f('ix_transacoes_mes'), table_name='transacoes')
    op.drop_index(op.f('ix_transacoes_item'), table_name='transacoes')
    op.drop_index(op.f('ix_transacoes_id'), table_name='transacoes')
    op.drop_index(op.f('ix_transacoes_categoria'), table_name='transacoes')
    op.drop_index(op.f('ix_transacoes_ano'), table_name='transacoes')
    op.drop_table('transacoes')
    op.drop_index(op.f('ix_investment_assets_ticker'), table_name='investment_assets')
    op.drop_index(op.f('ix_investment_assets_owner_id'), table_name='investment_assets')
    op.drop_index(op.f('ix_investment_assets_id'), table_name='investment_assets')
    op.drop_index(op.f('ix_investment_assets_company'), table_name='investment_assets')
    op.drop_table('investment_assets')
    op.drop_index(op.f('ix_categorias_tipo_id'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_owner_id'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_nome'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tipos_nome'), table_name='tipos')
    op.drop_index(op.f('ix_tipos_id'), table_name='tipos')
    op.drop_table('tipos')
    # ### end Alembic commands ###
